version: "2"

run:
  tests: false

linters:
  default: all
  disable:
    - wrapcheck
    - varnamelen
    - tagliatelle
    # - revive
    - paralleltest
    - containedctx
    - mnd
    - lll
    - ireturn
    - gocognit
    - gochecknoglobals
    - funlen
    - nonamedreturns
    - forcetypeassert
    - exhaustruct
    - exhaustive
    - err113
    - depguard
    - cyclop
    - gocyclo
    - maintidx
    - nestif
